[setup]
frontend = {cmd = "yarn", working_dir = "crates/frontend"}

[dev]
backend = {cmd = "cargo tauri dev", working_dir = "crates/backend"}
frontend = {cmd = "yarn dev", working_dir = "crates/frontend"}
